### ISSUE TITLE
allow HTML visualizations to define a web-font

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#517]
Currently web-fonts are used only for custom instance configurations of ANNIS but it should be possible that html visualizers can add a configurations which fonts should be available in their CSS.

Limitations in SCSS and the way we process the custom CSS (by wrapping it) it is currently not possible to add a `@font-face` into CSS for visualizers.

**Comment by thomaskrause** [comment]
The following generated SCSS works actually fine with the original Sass 3.4 compiler but fails with the Vaadin version:
```
.annis-wrapped-htmlvis-WhatsappMockup{
@font-face {
  font-family: 'Gloria Hallelujah';
  font-style: normal;
  font-weight: 400;
  src: local('Gloria Hallelujah'), local('GloriaHallelujah'), url(https://fonts.gstatic.com/s/gloriahallelujah/v8/CA1k7SlXcY5kvI81M_R28cNDay8z-hHR7F16xrcXsJw.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}

.message {
	border-color: black;
	border-style: solid;
	border-width: 1px;
	white-space: normal;
}
}
```
The error message is
```
SCHWERWIEGEND: encountered "@font-face". Was expecting one of: "}" "+" "-" ">" "~" "[" "*" "%" "&" "." "and" "or" "not" ":" "#{" "through" "in" "@include" "@debug" "@warn" "@for" "@each" "@while" "@if" "@extend" "@content" <MICROSOFT_RULE> <IDENT> <VARIABLE> <HASH> "@import" "@media" <KEY_FRAME_SYM> <ATKEYWORD> 
org.w3c.css.sac.CSSParseException: encountered "@font-face". Was expecting one of: "}" "+" "-" ">" "~" "[" "*" "%" "&" "." "and" "or" "not" ":" "#{" "through" "in" "@include" "@debug" "@warn" "@for" "@each" "@while" "@if" "@extend" "@content" <MICROSOFT_RULE> <IDENT> <VARIABLE> <HASH> "@import" "@media" <KEY_FRAME_SYM> <ATKEYWORD> 
	at com.vaadin.sass.internal.parser.Parser.reportError(Parser.java:418)
	at com.vaadin.sass.internal.parser.Parser.styleRule(Parser.java:2203)
	at com.vaadin.sass.internal.parser.Parser.topLevelDeclaration(Parser.java:591)
	at com.vaadin.sass.internal.parser.Parser.parserUnit(Parser.java:487)
	at com.vaadin.sass.internal.parser.Parser.parseStyleSheet(Parser.java:122)
	at com.vaadin.sass.internal.ScssStylesheet.get(ScssStylesheet.java:172)
	at com.vaadin.sass.internal.ScssStylesheet.get(ScssStylesheet.java:105)
	at com.vaadin.sass.internal.ScssStylesheet.get(ScssStylesheet.java:85)
	at annis.libgui.AnnisBaseUI.wrapCSS(AnnisBaseUI.java:414)
	at annis.libgui.AnnisBaseUI.injectUniqueCSS(AnnisBaseUI.java:388)
	at annis.visualizers.htmlvis.HTMLVis.createComponent(HTMLVis.java:163)
	at annis.visualizers.htmlvis.HTMLVis.createComponent(HTMLVis.java:1)
	at annis.gui.resultview.VisualizerPanel.createComponent(VisualizerPanel.java:262)
	at annis.gui.resultview.VisualizerPanel.access$500(VisualizerPanel.java:80)
	at annis.gui.resultview.VisualizerPanel$LoadComponentTask.call(VisualizerPanel.java:591)
	at annis.gui.resultview.VisualizerPanel$LoadComponentTask.call(VisualizerPanel.java:582)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
It seems like it should be actually be possible to directly use the `@font-face` in the SCSS file
